# Paste Primary
PastePrimaryKey=
# Number of entries
Number of entries=30
# Do not show password from password managers
IgnorePasswordFromPasswordManager=False
# Display passwords as plain text
ShowPassword=False
# Seconds before clearing password
ClearPasswordAfter=200

[TriggerKey]
0=Shift+Super+V

